### ISSUE TITLE
No display.:(

### ISSUE THREAD

**Issue by rjramirez** [paulopmx/Flexigrid#24] opened 2012-08-03 18:38 UTC
Here's my code.

<table id="flex1" style="display:none"></table>

``` javascript
/*
iso = mcode
name = mdescrip
printable_name = mtype
iso3 = mcolor
numcode = uom
*/
        $("#flex1").flexigrid({
    url: 'post-json.php',
    dataType: 'json',
    colModel : [
        {display: 'Code', name : 'mcode', width : 40, sortable : true, align: 'center'},
        {display: 'Description', name : 'mdescrip', width : 180, sortable : true, align: 'left'},
        {display: 'Type', name : 'mtype', width : 120, sortable : true, align: 'left'},
        {display: 'Color', name : 'mcolor', width : 130, sortable : true, align: 'left', hide: true},
        {display: 'UOM', name : 'uom', width : 80, sortable : true, align: 'right'}
        ],
    buttons : [
        {name: 'Add', bclass: 'add', onpress : test},
        {name: 'Delete', bclass: 'delete', onpress : test},
        {separator: true}
        ],
    searchitems : [
        {display: 'Code', name : 'mcode'},
        {display: 'Description', name : 'mdescrip', isdefault: true}
        ],
    sortname: "mcode",
    sortorder: "asc",
    usepager: true,
    title: 'Raw Materials',
    useRp: true,
    rp: 15,
    showTableToggleBtn: true,
    width: 700,
    height: 200
});   

        function test(com, grid) {
            if (com == 'Delete') {
                confirm('Delete ' + $('.trSelected', grid).length + ' items?')
            } else if (com == 'Add') {
                alert('Add New Item');
            }
        }
```

Below is the output of my post-json.php

{"page":1,"total":"284","rows":[[{"mcode":"Z","mdescrip":"Z","mtype":"Z","mcolor":"Z","uom":"Z"}],[{"mcode":"Z","mdescrip":"Z","mtype":"Z","mcolor":"Z","uom":"Z"}],[{"mcode":"P","mdescrip":"P","mtype":"P","mcolor":"P","uom":"P"}],[{"mcode":"P","mdescrip":"P","mtype":"P","mcolor":"P","uom":"P"}],[{"mcode":"Z","mdescrip":"Z","mtype":"Z","mcolor":"Z","uom":"Z"}],[{"mcode":"Z","mdescrip":"Z","mtype":"Z","mcolor":"Z","uom":"Z"}],[{"mcode":"B","mdescrip":"B","mtype":"B","mcolor":"B","uom":"B"}],[{"mcode":"B","mdescrip":"B","mtype":"B","mcolor":"B","uom":"B"}],[{"mcode":"r","mdescrip":"r","mtype":"r","mcolor":"r","uom":"r"}],[{"mcode":"r","mdescrip":"r","mtype":"r","mcolor":"r","uom":"r"}],[{"mcode":"0","mdescrip":"0","mtype":"0","mcolor":"0","uom":"0"}],[{"mcode":"0","mdescrip":"0","mtype":"0","mcolor":"0","uom":"0"}]]}

**Comment by rjramirez** [comment] 2012-08-04 05:02
my jquery is 1.7.2 and added no conflict script..

**Comment by paulopmx** [comment] 2012-08-15 05:07
Are you adding proper headers on your server-side script as well as using something similar with json_encode from PHP?

jQuery 1.6 up is very strict that you submit valid JSON responses or else it will not be processed by jquery.

**Comment by ecaron** [comment] 2012-10-17 04:57
Closing because nobody can reproduce this.

**Closed as completed by ecaron** 2012-10-17 04:57 UTC
